version: '3'

services:
  nginx-dev:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx-dev.conf:/etc/nginx/conf.d/default.conf
      - ./web:/web
    ports:
      - 80:80
    depends_on:
      - php-dev
      - mysql-dev

  php-dev:
    build:
      context: .
      dockerfile: php-dev.Dockerfile
    restart: always
    volumes:
      - ./web:/web
    depends_on:
      - mysql-dev

  mysql-dev:
    image: mysql:8.0.35
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8
      --collation-server=utf8_general_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_USER: 'username'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: 'initial_db'
    ports:
      - 3306:3306
    volumes:
      - mysqldata-dev:/var/lib/mysql

volumes:
  mysqldata-dev: {}
