services:
  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx-dev.conf:/etc/nginx/conf.d/default.conf
      - ./web:/var/www/web.twohoursonelife.com/web
      - ./data/diffDownloads:/var/www/web.twohoursonelife.com/web/public/downloads
      - ./data:/var/www/web.twohoursonelife.com/data
    ports:
      - 80:80
    depends_on:
      - php
      - mysql

  php:
    build: .
    restart: always
    volumes:
      - ./web:/var/www/web.twohoursonelife.com/web
      - ./data/diffDownloads:/var/www/web.twohoursonelife.com/web/public/downloads
      - ./data:/var/www/web.twohoursonelife.com/data
    depends_on:
      - mysql

  mysql:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_USER: 'username'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: 'twohoursonelife'
    ports:
      - 3306:3306
    volumes:
      - mysqldata-dev:/var/lib/mysql

volumes:
  mysqldata-dev: {}
