app = 'onelifeweb'
primary_region = 'ewr'

[build]
  build-target = 'runtime'

[http_service]
  internal_port = 8080
  min_machines_running = 1
  force_https = false

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    path = '/'

[[restart]]
  policy = 'on-failure'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'

[env]
  # Secrets
  # DB_HOST
  # DB_USER
  # DB_PASSWORD
  # DB_NAME

  # SHARED_GAME_SERVER_SECRET
  # PASSWORD_HASHING_PEPPER
  # SHARED_ENCRYPTION_SECRET
  # ACCESS_PASSWORD
