<?php

// Basic settings
// You must set these for the server to work
$databaseServer = getenv("DB_HOST");
$databaseUsername = getenv("DB_USER");
$databasePassword = getenv("DB_PASSWORD");
$databaseName = getenv("DB_NAME");

$mainSiteURL = get_site_url();

// Still referenced across multiple servers
$ticketServerURL = $mainSiteURL . "/ticketServer/server.php";

// secret shared with trusted game servers that allows them to post
// game stats

// MUST be changed from this default to prevent false game stats reporting.

// should not contain spaces
$sharedGameServerSecret = getenv("SHARED_GAME_SERVER_SECRET");


// should web-based admin require yubikey two-factor authentication?
$enableYubikey = 0;


// For hashing admin passwords so that they don't appear in the clear
// in this file.
// You can change this to your own string so that password hashes in
// this file differ from hashes of the same passwords used elsewhere.
$passwordHashingPepper = getenv("PASSWORD_HASHING_PEPPER");


// passwords are given as hashes below, computed by:
// hmac_sha1( $passwordHashingPepper,
//            hmac_sha1( $passwordHashingPepper, $password ) )
// Where $passwordHashingPepper is used as the hmac key.
// Client-side hashing sends the password to the server as:
//   hmac_sha1( $passwordHashingPepper, $password )
// The extra hash performed by the server prevents the hashes in
// this file from being used to login directly without knowing the actual
// password.

// For convenience, after setting a $passwordHashingPepper and chosing a
// password, hashes can be generated by invoking passwordHashUtility.php
// in your browser.

// default passwords that have been included as hashes below are:
// "secret" and "secret2"

// $accessPasswords = array( "8e409075ab35b161f6d2d57775e5efbee8d7b674",
//                           "20e1883a3d63607b60677dca87b41e04316ffc63" );

// hashes of passwords for for web-based admin access
$accessPasswords = array(getenv("ACCESS_PASSWORD"));

// secret used for encrypting a download code when it is requested for a
// given email address
// (for remote procedure calls that need to obtain a download code for a given
//  user)
// MUST replace this to keep ticket ids secret from outsiders
$sharedEncryptionSecret = getenv("SHARED_ENCRYPTION_SECRET");

function get_protocol()
{
    $protocol = 'http';

    if (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') {
        $protocol = 'https';
    } elseif (!empty($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') {
        // Account for proxies
        $protocol = 'https';
    }

    return $protocol;
}

function get_site_url(){
    return get_protocol() . "://" . $_SERVER['HTTP_HOST'];
}
